apiVersion: apps/v1
kind: Deployment
metadata:
  name: Lecture
  labels:
    app: Lecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Lecture
  template:
    metadata:
      labels:
        app: Lecture
    spec:
      containers:
        - name: Lecture
          image: username/Lecture:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5