apiVersion: apps/v1
kind: Deployment
metadata:
  name: RecommendSystem
  labels:
    app: RecommendSystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RecommendSystem
  template:
    metadata:
      labels:
        app: RecommendSystem
    spec:
      containers:
        - name: RecommendSystem
          image: username/RecommendSystem:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5